gwtbootstrap3/gwtbootstrap3-demo

src/main/java/org/gwtbootstrap3/demo/client/application/components/NavbarView.ui.xml
This fixes https://github.com/gwtbootstrap3/gwtbootstrap3/issues/246
=> Properly close tag

pom.xml
This is related to https://github.com/gwtbootstrap3/gwtbootstrap3/pull/259
=> Add gwt-user and gwt-dev dependencies

src/main/java/org/gwtbootstrap3/demo/client/application/extras/SummernoteView.ui.xml
If https://github.com/gwtbootstrap3/gwtbootstrap3-extras/pull/115 is merged.
=> Update summernote URL and version

src/main/java/org/gwtbootstrap3/demo/client/application/css/TypographyView.ui.xml
The source in the footer is different than the actual one used (and wrong actually).
=> Fix align -> alignment in source

src/main/java/org/gwtbootstrap3/demo/client/application/css/FormsView.ui.xml
=> More source corrections

pom.xml, src/main/java/org/gwtbootstrap3/demo/client/application/ApplicationModule.java, src/main/java/org/gwtbootstrap3/demo/client/application/ApplicationView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/Credentials.java, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/CredentialsEditor.java, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/CredentialsEditor.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/FormsValidationFactory.java, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/FormsWithValidationPresenter.java, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/FormsWithValidationView.java, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/FormsWithValidationView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/place/NameTokens.java, src/main/resources/org/gwtbootstrap3/demo/GwtBootstrap3Demo.gwt.xml
This is the example that illustrates error handling using JSR-303 validation.  I created ...css.validation package to hold the example.  It may be a bit excessive but the one example has 8 files.
=> Added example Forms w/Validation

src/main/java/org/gwtbootstrap3/demo/client/application/ApplicationModule.java, src/main/java/org/gwtbootstrap3/demo/client/application/ApplicationView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/TypeaheadPresenter.java, src/main/java/org/gwtbootstrap3/demo/client/application/extras/TypeaheadView.java, src/main/java/org/gwtbootstrap3/demo/client/application/extras/TypeaheadView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/place/NameTokens.java, src/main/resources/org/gwtbootstrap3/demo/GwtBootstrap3Demo.gwt.xml
Adds a demo for the new typeahead.js widget in gwtbootstrap3-extras. Please also see the corresponding pull request in gwtbootstrap3-extras:
https://github.com/gwtbootstrap3/gwtbootstrap3-extras/pull/131
=> Add demo for twitter typeahead.js.

.gitignore, src/main/java/org/gwtbootstrap3/demo/client/application/components/SuggestBoxView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/FormsWithValidationView.java, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/FormsWithValidationView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/FullCalendarView.java
Added examples for local validation to Forms w/Validation.
=> Local validation example

src/main/java/org/gwtbootstrap3/demo/client/application/extras/BootboxJSView.java, src/main/java/org/gwtbootstrap3/demo/client/application/extras/BootboxJSView.ui.xml
=> Added Bootbox Dialog example.

src/main/java/org/gwtbootstrap3/demo/client/application/ApplicationModule.java, src/main/java/org/gwtbootstrap3/demo/client/application/ApplicationView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/components/ButtonGroupView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/NotifyPresenter.java, src/main/java/org/gwtbootstrap3/demo/client/application/extras/NotifyView.java, src/main/java/org/gwtbootstrap3/demo/client/application/extras/NotifyView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/SliderView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/SummernoteView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/place/NameTokens.java, src/main/resources/org/gwtbootstrap3/demo/GwtBootstrap3Demo.gwt.xml
Also updated slider and summernote supported version.
=> Added first version of bootstrap notify demo

src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/CredentialsEditor.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/FormsWithValidationView.ui.xml, src/main/resources/org/gwtbootstrap3/client/ui/form/validator/ValidationMessages_en.properties, src/main/resources/org/gwtbootstrap3/client/ui/form/validator/ValidationMessages_fr.properties, src/main/resources/org/gwtbootstrap3/demo/GwtBootstrap3Demo.gwt.xml, src/main/resources/org/hibernate/validator/ValidationMessages_en.properties, src/main/resources/org/hibernate/validator/ValidationMessages_fr.properties
Added showRequiredIndicator to the FormLabel.
Added french validation message for the local Blank validation message and the hibernate NotNull validation message.
Added the french locale to the gwt.xml module.
Updated the FormWithValidationView to show how to localize the validation messages.
=> Update to forms with validation, including i18n example.

src/main/java/org/gwtbootstrap3/demo/client/application/extras/FullCalendarView.java, src/main/java/org/gwtbootstrap3/demo/client/application/extras/FullCalendarView.ui.xml
Added additional calendar example to show background events feature.
=> FullCalendar update to 2.3.1

src/main/java/org/gwtbootstrap3/demo/client/application/javascript/ModalView.ui.xml
These changes are no longer necessary as a result of https://github.com/gwtbootstrap3/gwtbootstrap3/pull/400
=> Reverted changes for PR #86 as a result of PR #400.

src/main/java/org/gwtbootstrap3/demo/client/application/javascript/ModalView.java
When creating Modal, it would better to call setRemoveOnHide(true)
=> Improved Modal demo

pom.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/DatePickerView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/DateTimePickerView.ui.xml
Added demo validation to basic DatePicker and DateTimePicker. Increased compile memory requirement.
=> Added blank validation test to basic DatePicker and DateTimePicker.

src/main/java/org/gwtbootstrap3/demo/client/application/ApplicationModule.java, src/main/java/org/gwtbootstrap3/demo/client/application/ApplicationView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/GalleryPresenter.java, src/main/java/org/gwtbootstrap3/demo/client/application/extras/GalleryView.java, src/main/java/org/gwtbootstrap3/demo/client/application/extras/GalleryView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/place/NameTokens.java, src/main/resources/org/gwtbootstrap3/demo/GwtBootstrap3Demo.gwt.xml
https://github.com/gwtbootstrap3/gwtbootstrap3-extras/pull/224
Can add more examples later.
=> Added a demo for the new Gallery

pom.xml, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/FormsWithValidationView.java, src/main/java/org/gwtbootstrap3/demo/client/application/css/validation/FormsWithValidationView.ui.xml
Added submitOnEnter demo.  Updated gwtp to 1.5.1.
=> Added submitOnEnter demo.

src/main/java/org/gwtbootstrap3/demo/client/application/extras/BootstrapSelectView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/GalleryView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/SliderView.ui.xml
=> Fixed menu collapse issue on mobile devices

src/main/java/org/gwtbootstrap3/demo/client/application/extras/DateTimePickerView.java, src/main/java/org/gwtbootstrap3/demo/client/application/extras/DateTimePickerView.ui.xml
=> Updated datetime picker demo to 2.3.8

src/main/java/org/gwtbootstrap3/demo/client/application/javascript/PopoverView.ui.xml
Only the `title` attribute was written, but the `content` attribute is also important.
=> Add ` content="..."` in example code.

src/main/java/org/gwtbootstrap3/demo/client/application/javascript/CarouselView.ui.xml
=> Updated carousel demo

src/main/java/org/gwtbootstrap3/demo/client/application/ApplicationModule.java, src/main/java/org/gwtbootstrap3/demo/client/application/ApplicationView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/TagsInputPresenter.java, src/main/java/org/gwtbootstrap3/demo/client/application/extras/TagsInputView.java, src/main/java/org/gwtbootstrap3/demo/client/application/extras/TagsInputView.ui.xml, src/main/java/org/gwtbootstrap3/demo/client/place/NameTokens.java, src/main/resources/org/gwtbootstrap3/demo/GwtBootstrap3Demo.gwt.xml
Demo page for Bootstrap Tags Input
=> Demo page for Bootstrap Tags Input

pom.xml, src/main/java/org/gwtbootstrap3/demo/client/application/extras/SliderView.ui.xml
Also updated gwt-platform to 1.5.3
=> Updated slider demo to 6.1.8
